name: datalake-buckets
path: git::https://github.com/awslabs/autonomous-driving-data-framework.git//modules/optionals/datalake-buckets
parameters:
  - name: encryption-type
    value: SSE
---
name: networking
path: git::https://github.com/awslabs/idf-modules.git//modules/network/basic-cdk?ref=release/1.4.0&depth=1
parameters:
  - name: internet-accessible
    value: false
---
name: ecr-ml-images
path: git::https://github.com/awslabs/idf-modules.git//modules/storage/ecr?ref=release/1.4.1&depth=1
parameters:
  - name: repository-name
    value: ml-mnist-images
  - name: image-tag-mutability
    value: "MUTABLE"
  - name: lifecycle-max-image-count
    value: 10
