name: datalake-buckets
path: git::https://github.com/awslabs/autonomous-driving-data-framework.git//modules/optionals/datalake-buckets
parameters:
  - name: encryption-type
    value: SSE
---
name: networking
path: git::https://github.com/awslabs/idf-modules.git//modules/network/basic-cdk
parameters:
  - name: internet-accessible
    value: false